-- Catálogo global: modelos Samsung Galaxy (marca SAMSUNG, tipo CELULAR)
-- Pré-requisitos: aparelhos_catalogo.sql, equipamentos_tipos_catalogo.sql, marcas_catalogo.sql
-- Duplicatas (marca + modelo) são ignoradas (ON CONFLICT DO NOTHING)
-- Total: 239 modelos

INSERT INTO public.aparelhos_catalogo (marca, modelo, tipo, tipo_id, ativo)
SELECT
  'SAMSUNG',
  v.modelo,
  'CELULAR',
  t.id,
  true
FROM (
  VALUES
    ('GALAXY S6'),
    ('GALAXY S6 EDGE'),
    ('GALAXY S6 EDGE+'),
    ('GALAXY S7'),
    ('GALAXY S7 EDGE'),
    ('GALAXY S8'),
    ('GALAXY S8+'),
    ('GALAXY S8 ACTIVE'),
    ('GALAXY S9'),
    ('GALAXY S9+'),
    ('GALAXY S10E'),
    ('GALAXY S10'),
    ('GALAXY S10+'),
    ('GALAXY S10 5G'),
    ('GALAXY S10 LITE'),
    ('GALAXY S20'),
    ('GALAXY S20+'),
    ('GALAXY S20 ULTRA'),
    ('GALAXY S20 FE'),
    ('GALAXY S20 FE 5G'),
    ('GALAXY S21'),
    ('GALAXY S21+'),
    ('GALAXY S21 ULTRA'),
    ('GALAXY S21 FE'),
    ('GALAXY S22'),
    ('GALAXY S22+'),
    ('GALAXY S22 ULTRA'),
    ('GALAXY S23'),
    ('GALAXY S23+'),
    ('GALAXY S23 ULTRA'),
    ('GALAXY S23 FE'),
    ('GALAXY S24'),
    ('GALAXY S24+'),
    ('GALAXY S24 ULTRA'),
    ('GALAXY S24 FE'),
    ('GALAXY S25'),
    ('GALAXY S25+'),
    ('GALAXY S25 ULTRA'),
    ('GALAXY S25 EDGE'),
    ('GALAXY S25 FE'),
    ('GALAXY S26'),
    ('GALAXY S26+'),
    ('GALAXY S26 ULTRA'),
    ('GALAXY NOTE5'),
    ('GALAXY NOTE7'),
    ('GALAXY NOTE FE'),
    ('GALAXY NOTE8'),
    ('GALAXY NOTE9'),
    ('GALAXY NOTE10'),
    ('GALAXY NOTE10+'),
    ('GALAXY NOTE10 LITE'),
    ('GALAXY NOTE10+ 5G'),
    ('GALAXY NOTE20'),
    ('GALAXY NOTE20 5G'),
    ('GALAXY NOTE20 ULTRA'),
    ('GALAXY NOTE20 ULTRA 5G'),
    ('GALAXY FOLD'),
    ('GALAXY Z FOLD2'),
    ('GALAXY Z FOLD3'),
    ('GALAXY Z FOLD4'),
    ('GALAXY Z FOLD5'),
    ('GALAXY Z FOLD6'),
    ('GALAXY Z FOLD7'),
    ('GALAXY Z FLIP'),
    ('GALAXY Z FLIP 5G'),
    ('GALAXY Z FLIP3'),
    ('GALAXY Z FLIP4'),
    ('GALAXY Z FLIP5'),
    ('GALAXY Z FLIP6'),
    ('GALAXY Z FLIP7'),
    ('GALAXY Z FLIP7 FE'),
    ('GALAXY Z TRIFOLD'),
    ('GALAXY A01'),
    ('GALAXY A01 CORE'),
    ('GALAXY A02'),
    ('GALAXY A02S'),
    ('GALAXY A03'),
    ('GALAXY A03 CORE'),
    ('GALAXY A03S'),
    ('GALAXY A04'),
    ('GALAXY A04E'),
    ('GALAXY A04S'),
    ('GALAXY A05'),
    ('GALAXY A05S'),
    ('GALAXY A06'),
    ('GALAXY A06 5G'),
    ('GALAXY A10'),
    ('GALAXY A10E'),
    ('GALAXY A10S'),
    ('GALAXY A11'),
    ('GALAXY A12'),
    ('GALAXY A13'),
    ('GALAXY A13 5G'),
    ('GALAXY A14'),
    ('GALAXY A14 5G'),
    ('GALAXY A15'),
    ('GALAXY A15 5G'),
    ('GALAXY A16'),
    ('GALAXY A16 5G'),
    ('GALAXY A17'),
    ('GALAXY A17 5G'),
    ('GALAXY A20'),
    ('GALAXY A20E'),
    ('GALAXY A20S'),
    ('GALAXY A21'),
    ('GALAXY A21S'),
    ('GALAXY A22'),
    ('GALAXY A22 5G'),
    ('GALAXY A23'),
    ('GALAXY A23 5G'),
    ('GALAXY A24'),
    ('GALAXY A25 5G'),
    ('GALAXY A26 5G'),
    ('GALAXY A30'),
    ('GALAXY A30S'),
    ('GALAXY A31'),
    ('GALAXY A32'),
    ('GALAXY A32 5G'),
    ('GALAXY A33 5G'),
    ('GALAXY A34 5G'),
    ('GALAXY A35 5G'),
    ('GALAXY A36 5G'),
    ('GALAXY A37 5G'),
    ('GALAXY A40'),
    ('GALAXY A40S'),
    ('GALAXY A41'),
    ('GALAXY A42 5G'),
    ('GALAXY A50'),
    ('GALAXY A50S'),
    ('GALAXY A51'),
    ('GALAXY A51 5G'),
    ('GALAXY A52'),
    ('GALAXY A52 5G'),
    ('GALAXY A52S 5G'),
    ('GALAXY A53 5G'),
    ('GALAXY A54 5G'),
    ('GALAXY A55 5G'),
    ('GALAXY A56 5G'),
    ('GALAXY A57 5G'),
    ('GALAXY A60'),
    ('GALAXY A70'),
    ('GALAXY A70S'),
    ('GALAXY A71'),
    ('GALAXY A71 5G'),
    ('GALAXY A72'),
    ('GALAXY A73 5G'),
    ('GALAXY A80'),
    ('GALAXY A90 5G'),
    ('GALAXY M01'),
    ('GALAXY M01 CORE'),
    ('GALAXY M01S'),
    ('GALAXY M02'),
    ('GALAXY M02S'),
    ('GALAXY M04'),
    ('GALAXY M10'),
    ('GALAXY M10S'),
    ('GALAXY M11'),
    ('GALAXY M12'),
    ('GALAXY M13'),
    ('GALAXY M13 5G'),
    ('GALAXY M14 5G'),
    ('GALAXY M15 5G'),
    ('GALAXY M16 5G'),
    ('GALAXY M20'),
    ('GALAXY M21'),
    ('GALAXY M21S'),
    ('GALAXY M22'),
    ('GALAXY M23 5G'),
    ('GALAXY M30'),
    ('GALAXY M30S'),
    ('GALAXY M31'),
    ('GALAXY M31S'),
    ('GALAXY M32'),
    ('GALAXY M32 5G'),
    ('GALAXY M33 5G'),
    ('GALAXY M34 5G'),
    ('GALAXY M35 5G'),
    ('GALAXY M36 5G'),
    ('GALAXY M40'),
    ('GALAXY M42 5G'),
    ('GALAXY M44 5G'),
    ('GALAXY M51'),
    ('GALAXY M52 5G'),
    ('GALAXY M53 5G'),
    ('GALAXY M54 5G'),
    ('GALAXY M55 5G'),
    ('GALAXY M55S 5G'),
    ('GALAXY M56 5G'),
    ('GALAXY M62'),
    ('GALAXY F02S'),
    ('GALAXY F04'),
    ('GALAXY F05'),
    ('GALAXY F12'),
    ('GALAXY F13'),
    ('GALAXY F14 5G'),
    ('GALAXY F15 5G'),
    ('GALAXY F16 5G'),
    ('GALAXY F22'),
    ('GALAXY F23 5G'),
    ('GALAXY F34 5G'),
    ('GALAXY F41'),
    ('GALAXY F42 5G'),
    ('GALAXY F52 5G'),
    ('GALAXY F54 5G'),
    ('GALAXY F55 5G'),
    ('GALAXY F56 5G'),
    ('GALAXY F62'),
    ('GALAXY J1'),
    ('GALAXY J1 ACE'),
    ('GALAXY J1 MINI'),
    ('GALAXY J1 MINI PRIME'),
    ('GALAXY J2'),
    ('GALAXY J2 CORE'),
    ('GALAXY J2 PRIME'),
    ('GALAXY J2 PRO'),
    ('GALAXY J3'),
    ('GALAXY J3 PRO'),
    ('GALAXY J3 PRIME'),
    ('GALAXY J4'),
    ('GALAXY J4+'),
    ('GALAXY J4 CORE'),
    ('GALAXY J5'),
    ('GALAXY J5 PRIME'),
    ('GALAXY J5 PRO'),
    ('GALAXY J6'),
    ('GALAXY J6+'),
    ('GALAXY J7'),
    ('GALAXY J7 PRIME'),
    ('GALAXY J7 PRO'),
    ('GALAXY J7 NEO'),
    ('GALAXY J7 MAX'),
    ('GALAXY J7 DUO'),
    ('GALAXY J8'),
    ('GALAXY XCOVER 4'),
    ('GALAXY XCOVER 4S'),
    ('GALAXY XCOVER 5'),
    ('GALAXY XCOVER 6 PRO'),
    ('GALAXY XCOVER 7'),
    ('GALAXY XCOVER 7 PRO')
) AS v(modelo)
CROSS JOIN LATERAL (
  SELECT id
  FROM public.equipamentos_tipos_catalogo
  WHERE codigo = 'CELULAR' AND ativo = true
  ORDER BY ordem NULLS LAST, created_at
  LIMIT 1
) AS t
ON CONFLICT ON CONSTRAINT aparelhos_catalogo_marca_modelo_unique DO NOTHING;
