-- Catálogo global: modelos Motorola (marca MOTOROLA, tipo CELULAR)
-- Pré-requisitos: aparelhos_catalogo.sql, equipamentos_tipos_catalogo.sql, marcas_catalogo.sql
-- Duplicatas (marca + modelo) são ignoradas (ON CONFLICT DO NOTHING)
-- Total: 163 modelos (2 duplicata(s) na lista original removida(s))

INSERT INTO public.aparelhos_catalogo (marca, modelo, tipo, tipo_id, ativo)
SELECT
  'MOTOROLA',
  v.modelo,
  'CELULAR',
  t.id,
  true
FROM (
  VALUES
    ('MOTO G'),
    ('MOTO G 2ª GERAÇÃO'),
    ('MOTO G 3ª GERAÇÃO'),
    ('MOTO G4'),
    ('MOTO G4 PLAY'),
    ('MOTO G4 PLUS'),
    ('MOTO G5'),
    ('MOTO G5 PLUS'),
    ('MOTO G5S'),
    ('MOTO G5S PLUS'),
    ('MOTO G6'),
    ('MOTO G6 PLAY'),
    ('MOTO G6 PLUS'),
    ('MOTO G7'),
    ('MOTO G7 PLAY'),
    ('MOTO G7 PLUS'),
    ('MOTO G7 POWER'),
    ('MOTO G8'),
    ('MOTO G8 PLAY'),
    ('MOTO G8 PLUS'),
    ('MOTO G8 POWER'),
    ('MOTO G8 POWER LITE'),
    ('MOTO G9'),
    ('MOTO G9 PLAY'),
    ('MOTO G9 PLUS'),
    ('MOTO G9 POWER'),
    ('MOTO G10'),
    ('MOTO G10 POWER'),
    ('MOTO G20'),
    ('MOTO G30'),
    ('MOTO G40 FUSION'),
    ('MOTO G50'),
    ('MOTO G50 5G'),
    ('MOTO G60'),
    ('MOTO G60S'),
    ('MOTO G71 5G'),
    ('MOTO G72'),
    ('MOTO G73 5G'),
    ('MOTO G82 5G'),
    ('MOTO G100'),
    ('MOTO G200 5G'),
    ('MOTO G13'),
    ('MOTO G14'),
    ('MOTO G22'),
    ('MOTO G23'),
    ('MOTO G24'),
    ('MOTO G24 POWER'),
    ('MOTO G31'),
    ('MOTO G32'),
    ('MOTO G34 5G'),
    ('MOTO G41'),
    ('MOTO G42'),
    ('MOTO G52'),
    ('MOTO G53 5G'),
    ('MOTO G54 5G'),
    ('MOTO G62 5G'),
    ('MOTO G84 5G'),
    ('MOTO G04'),
    ('MOTO G04S'),
    ('MOTO G05'),
    ('MOTO G15'),
    ('MOTO G15 POWER'),
    ('MOTO G35 5G'),
    ('MOTO G45 5G'),
    ('MOTO G55 5G'),
    ('MOTO G75 5G'),
    ('MOTO G85 5G'),
    ('MOTO E'),
    ('MOTO E 2ª GERAÇÃO'),
    ('MOTO E3'),
    ('MOTO E3 POWER'),
    ('MOTO E4'),
    ('MOTO E4 PLUS'),
    ('MOTO E5'),
    ('MOTO E5 PLAY'),
    ('MOTO E5 PLUS'),
    ('MOTO E6'),
    ('MOTO E6 PLAY'),
    ('MOTO E6 PLUS'),
    ('MOTO E6S'),
    ('MOTO E7'),
    ('MOTO E7 PLUS'),
    ('MOTO E7 POWER'),
    ('MOTO E20'),
    ('MOTO E22'),
    ('MOTO E22I'),
    ('MOTO E30'),
    ('MOTO E32'),
    ('MOTO E32S'),
    ('MOTO E40'),
    ('MOTO E13'),
    ('MOTO E14'),
    ('EDGE'),
    ('EDGE+'),
    ('EDGE 20'),
    ('EDGE 20 LITE'),
    ('EDGE 20 PRO'),
    ('EDGE 30'),
    ('EDGE 30 NEO'),
    ('EDGE 30 FUSION'),
    ('EDGE 30 PRO'),
    ('EDGE 30 ULTRA'),
    ('EDGE 40'),
    ('EDGE 40 NEO'),
    ('EDGE 40 PRO'),
    ('EDGE 50'),
    ('EDGE 50 NEO'),
    ('EDGE 50 FUSION'),
    ('EDGE 50 PRO'),
    ('EDGE 50 ULTRA'),
    ('EDGE 60'),
    ('EDGE 60 FUSION'),
    ('EDGE 60 PRO'),
    ('EDGE 60 ULTRA'),
    ('RAZR'),
    ('RAZR V3'),
    ('RAZR V3I'),
    ('RAZR V3X'),
    ('RAZR V3XX'),
    ('RAZR2 V8'),
    ('RAZR2 V9'),
    ('RAZR 2019'),
    ('RAZR 5G'),
    ('RAZR 2022'),
    ('RAZR 40'),
    ('RAZR 40 ULTRA'),
    ('RAZR 50'),
    ('RAZR 50 ULTRA'),
    ('RAZR 60'),
    ('RAZR 60 ULTRA'),
    ('ONE'),
    ('ONE POWER'),
    ('ONE VISION'),
    ('ONE ACTION'),
    ('ONE ZOOM'),
    ('ONE MACRO'),
    ('ONE FUSION'),
    ('ONE FUSION+'),
    ('ONE 5G'),
    ('ONE 5G ACE'),
    ('ONE HYPER'),
    ('MOTO X'),
    ('MOTO X 2ª GERAÇÃO'),
    ('MOTO X PLAY'),
    ('MOTO X STYLE'),
    ('MOTO X FORCE'),
    ('MOTO X4'),
    ('MOTO Z'),
    ('MOTO Z PLAY'),
    ('MOTO Z FORCE'),
    ('MOTO Z2 PLAY'),
    ('MOTO Z2 FORCE'),
    ('MOTO Z3'),
    ('MOTO Z3 PLAY'),
    ('MOTO Z4'),
    ('DEFY'),
    ('DEFY 2021'),
    ('DEFY 2'),
    ('DROID TURBO'),
    ('DROID TURBO 2'),
    ('DROID MAXX'),
    ('DROID MINI'),
    ('DROID ULTRA')
) AS v(modelo)
CROSS JOIN LATERAL (
  SELECT id
  FROM public.equipamentos_tipos_catalogo
  WHERE codigo = 'CELULAR' AND ativo = true
  ORDER BY ordem NULLS LAST, created_at
  LIMIT 1
) AS t
ON CONFLICT ON CONSTRAINT aparelhos_catalogo_marca_modelo_unique DO NOTHING;
