-- Catálogo global: modelos Xiaomi (marca XIAOMI, tipo CELULAR)
-- Pré-requisitos: aparelhos_catalogo.sql, equipamentos_tipos_catalogo.sql, marcas_catalogo.sql
-- Duplicatas (marca + modelo) são ignoradas (ON CONFLICT DO NOTHING)
-- Total: 186 modelos (0 duplicata(s) na lista original removida(s))

INSERT INTO public.aparelhos_catalogo (marca, modelo, tipo, tipo_id, ativo)
SELECT
  'XIAOMI',
  v.modelo,
  'CELULAR',
  t.id,
  true
FROM (
  VALUES
    ('MI 8'),
    ('MI 8 LITE'),
    ('MI 8 PRO'),
    ('MI 9'),
    ('MI 9 SE'),
    ('MI 9 LITE'),
    ('MI 9T'),
    ('MI 9T PRO'),
    ('MI 10'),
    ('MI 10 PRO'),
    ('MI 10 LITE'),
    ('MI 10T'),
    ('MI 10T LITE'),
    ('MI 10T PRO'),
    ('MI 11'),
    ('MI 11 LITE'),
    ('MI 11 LITE 5G'),
    ('MI 11I'),
    ('MI 11 ULTRA'),
    ('MI 11T'),
    ('MI 11T PRO'),
    ('11 LITE 5G NE'),
    ('11T'),
    ('11T PRO'),
    ('12'),
    ('12 PRO'),
    ('12 LITE'),
    ('12X'),
    ('12T'),
    ('12T PRO'),
    ('13'),
    ('13 LITE'),
    ('13 PRO'),
    ('13 ULTRA'),
    ('13T'),
    ('13T PRO'),
    ('14'),
    ('14 PRO'),
    ('14 ULTRA'),
    ('14T'),
    ('14T PRO'),
    ('15'),
    ('15 PRO'),
    ('15 ULTRA'),
    ('15T'),
    ('15T PRO'),
    ('MIX'),
    ('MI MIX 2'),
    ('MI MIX 2S'),
    ('MI MIX 3'),
    ('MI MIX 3 5G'),
    ('MIX 4'),
    ('MIX FOLD'),
    ('MIX FOLD 2'),
    ('MIX FOLD 3'),
    ('MIX FOLD 4'),
    ('MIX FLIP'),
    ('MI A1'),
    ('MI A2'),
    ('MI A2 LITE'),
    ('MI A3'),
    ('REDMI 6'),
    ('REDMI 6A'),
    ('REDMI 7'),
    ('REDMI 7A'),
    ('REDMI 8'),
    ('REDMI 8A'),
    ('REDMI 8A PRO'),
    ('REDMI 9'),
    ('REDMI 9A'),
    ('REDMI 9C'),
    ('REDMI 9T'),
    ('REDMI 10'),
    ('REDMI 10A'),
    ('REDMI 10C'),
    ('REDMI 2022'),
    ('REDMI 12'),
    ('REDMI 12C'),
    ('REDMI 13'),
    ('REDMI 13C'),
    ('REDMI 13C 5G'),
    ('REDMI 14C'),
    ('REDMI A1'),
    ('REDMI A1+'),
    ('REDMI A2'),
    ('REDMI A2+'),
    ('REDMI A3'),
    ('REDMI A3X'),
    ('REDMI A4 5G'),
    ('REDMI A5'),
    ('REDMI NOTE 6 PRO'),
    ('REDMI NOTE 7'),
    ('REDMI NOTE 7 PRO'),
    ('REDMI NOTE 8'),
    ('REDMI NOTE 8 PRO'),
    ('REDMI NOTE 8T'),
    ('REDMI NOTE 9'),
    ('REDMI NOTE 9S'),
    ('REDMI NOTE 9 PRO'),
    ('REDMI NOTE 9 PRO MAX'),
    ('REDMI NOTE 10'),
    ('REDMI NOTE 10S'),
    ('REDMI NOTE 10 5G'),
    ('REDMI NOTE 10 PRO'),
    ('REDMI NOTE 10 PRO MAX'),
    ('REDMI NOTE 11'),
    ('REDMI NOTE 11S'),
    ('REDMI NOTE 11S 5G'),
    ('REDMI NOTE 11 PRO'),
    ('REDMI NOTE 11 PRO 5G'),
    ('REDMI NOTE 11 PRO+ 5G'),
    ('REDMI NOTE 12'),
    ('REDMI NOTE 12 5G'),
    ('REDMI NOTE 12S'),
    ('REDMI NOTE 12 PRO'),
    ('REDMI NOTE 12 PRO 5G'),
    ('REDMI NOTE 12 PRO+ 5G'),
    ('REDMI NOTE 13'),
    ('REDMI NOTE 13 5G'),
    ('REDMI NOTE 13 PRO'),
    ('REDMI NOTE 13 PRO 5G'),
    ('REDMI NOTE 13 PRO+ 5G'),
    ('REDMI NOTE 14'),
    ('REDMI NOTE 14 5G'),
    ('REDMI NOTE 14 PRO'),
    ('REDMI NOTE 14 PRO 5G'),
    ('REDMI NOTE 14 PRO+ 5G'),
    ('REDMI NOTE 15'),
    ('REDMI NOTE 15 PRO'),
    ('REDMI NOTE 15 PRO+'),
    ('POCO F1'),
    ('POCO F2 PRO'),
    ('POCO F3'),
    ('POCO F3 GT'),
    ('POCO F4'),
    ('POCO F4 GT'),
    ('POCO F5'),
    ('POCO F5 PRO'),
    ('POCO F6'),
    ('POCO F6 PRO'),
    ('POCO F7'),
    ('POCO F7 PRO'),
    ('POCO F7 ULTRA'),
    ('POCO F8 PRO'),
    ('POCO F8 ULTRA'),
    ('POCO X2'),
    ('POCO X3'),
    ('POCO X3 NFC'),
    ('POCO X3 PRO'),
    ('POCO X3 GT'),
    ('POCO X4 PRO 5G'),
    ('POCO X4 GT'),
    ('POCO X5'),
    ('POCO X5 PRO 5G'),
    ('POCO X6'),
    ('POCO X6 PRO'),
    ('POCO X7'),
    ('POCO X7 PRO'),
    ('POCO X8 PRO'),
    ('POCO X8 PRO MAX'),
    ('POCO M2'),
    ('POCO M2 PRO'),
    ('POCO M3'),
    ('POCO M3 PRO 5G'),
    ('POCO M4'),
    ('POCO M4 PRO'),
    ('POCO M4 PRO 5G'),
    ('POCO M5'),
    ('POCO M5S'),
    ('POCO M6'),
    ('POCO M6 PRO'),
    ('POCO M6 PRO 5G'),
    ('POCO M7'),
    ('POCO M7 PRO 5G'),
    ('POCO M8 5G'),
    ('POCO M8 PRO 5G'),
    ('POCO C3'),
    ('POCO C31'),
    ('POCO C40'),
    ('POCO C50'),
    ('POCO C51'),
    ('POCO C55'),
    ('POCO C61'),
    ('POCO C65'),
    ('POCO C75'),
    ('POCO C85')
) AS v(modelo)
CROSS JOIN LATERAL (
  SELECT id
  FROM public.equipamentos_tipos_catalogo
  WHERE codigo = 'CELULAR' AND ativo = true
  ORDER BY ordem NULLS LAST, created_at
  LIMIT 1
) AS t
ON CONFLICT ON CONSTRAINT aparelhos_catalogo_marca_modelo_unique DO NOTHING;
