#!/bin/bash

echo "🔍 DIAGNÓSTICO DO DEPLOY - VPS"
echo "================================"
echo ""

echo "1️⃣ Verificando conectividade SSH..."
echo "Testando conexão com o VPS..."

echo ""
echo "2️⃣ Verificando estrutura do projeto no VPS..."
echo "Diretório: /opt/gestaoconsert"
echo "Arquivos esperados:"
echo "  - package.json"
echo "  - yarn.lock"
echo "  - Dockerfile"
echo "  - docker-compose.yml"
echo "  - .github/workflows/deploy.yml"

echo ""
echo "3️⃣ Comandos que devem ser executados no VPS:"
echo "  cd /opt/gestaoconsert"
echo "  git pull origin main"
echo "  yarn build"
echo "  docker-compose down"
echo "  docker-compose up -d"

echo ""
echo "4️⃣ Possíveis problemas:"
echo "  ❌ Credenciais SSH inválidas"
echo "  ❌ VPS inacessível"
echo "  ❌ Diretório /opt/gestaoconsert não existe"
echo "  ❌ Permissões insuficientes"
echo "  ❌ Docker não instalado no VPS"
echo "  ❌ Yarn não instalado no VPS"

echo ""
echo "5️⃣ Soluções recomendadas:"
echo "  ✅ Verificar secrets do GitHub Actions"
echo "  ✅ Testar SSH manualmente"
echo "  ✅ Verificar se o VPS está online"
echo "  ✅ Instalar Docker no VPS"
echo "  ✅ Instalar Yarn no VPS"
echo "  ✅ Verificar permissões do usuário"

echo ""
echo "📋 Para debug manual no VPS:"
echo "  ssh usuario@vps-ip"
echo "  cd /opt/gestaoconsert"
echo "  ls -la"
echo "  git status"
echo "  docker --version"
echo "  yarn --version"
